### ISSUE TITLE
internal/modules/cjs/loader.js:638

### ISSUE THREAD

**Issue by jayjamesdr** [armory3d/armorpaint#1066]
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/jayjames/tmp/armorcore/make'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

rm -rf node_modules package-lock.json && npm install && npm start : this is not working

**Comment by luboslenco** [comment]
Hello, use a recursive clone.

`git clone --recursive https://github.com/armory3d/armorpaint`
