### ISSUE TITLE
Updating and compiling cloned repo

### ISSUE THREAD

**Issue by knightknight** [armory3d/armorpaint#184]
The first time I `git clone` this repo and followed the [compile instructions](https://github.com/armory3d/armorpaint) I was successful. However each time I have tried updating an already cloned repo with `git pull`, then following the [compile instructions](https://github.com/armory3d/armorpaint) I get `Haxe compiler error.`.

The only way I been able to get a successful rebuild is to delete the armorpaint directory and start the clone process again. 

Unless I should just be update the `git pull` then re-run Visual Studio to compile the latest version?

- Windows 10
- git version 2.23.0.windows.1
- node v12.11.1
- visual studio 2019 community
- Microsoft Visual Studio Community 2019 Version 16.3.3
- Microsoft .NET Framework Version 4.8.03752

```
PS C:\> cd .\armorpaint\
PS C:\armorpaint> git pull
Already up to date.
PS C:\armorpaint> node Kromx/make -g direct3d11
Using Kha from C:\armorpaint\Kromx
Creating Kha project.
Exporting asset 1 of 12 (brdf.png).
Exporting asset 2 of 12 (color_wheel.png).
Exporting asset 3 of 12 (config.arm).
Exporting asset 4 of 12 (cursor.png).
Exporting asset 5 of 12 (font13.bin).
Exporting asset 6 of 12 (icons.png).
Exporting asset 7 of 12 (icons2x.png).
Exporting asset 8 of 12 (noise256.png).
Exporting asset 9 of 12 (shader_datas.arm).
Exporting asset 10 of 12 (smaa_area.png).
Exporting asset 11 of 12 (smaa_search.png).
Exporting asset 12 of 12 (font_default.ttf).
Exporting asset 1 of 2 (default_brush.json).
Exporting asset 2 of 2 (default_material.json).
Exporting asset 1 of 13 (authors.md).
Exporting asset 2 of 13 (license.md).
Exporting asset 3 of 13 (license_cmft.md).
Exporting asset 4 of 13 (license_cycles-nodes.md).
Exporting asset 5 of 13 (license_heapsfbx.md).
Exporting asset 6 of 13 (license_hxformat.md).
Exporting asset 7 of 13 (license_hxpako.md).
Exporting asset 8 of 13 (license_kinc.md).
Exporting asset 9 of 13 (license_krom.md).
Exporting asset 10 of 13 (license_lz4-wasm.md).
Exporting asset 11 of 13 (license_kha.md).
Exporting asset 12 of 13 (license_nfd.md).
Exporting asset 13 of 13 (license_roboto.md).
Exporting asset 1 of 2 (plugin_hello.js).
Exporting asset 2 of 2 (plugin_rotate.js).
Exporting asset 1 of 1 (theme_light.arm).
Exporting asset 1 of 1 (readme.txt).
Exporting asset 1 of 1 (cmft.exe).
Exporting asset 1 of 18 (Scene.arm).
Exporting asset 2 of 18 (World.hdr).
Exporting asset 3 of 18 (World_irradiance.arm).
Exporting asset 4 of 18 (World_radiance.hdr).
Exporting asset 5 of 18 (World_radiance_0.hdr).
Exporting asset 6 of 18 (World_radiance_2.hdr).
Exporting asset 7 of 18 (World_radiance_3.hdr).
Exporting asset 8 of 18 (World_radiance_4.hdr).
Exporting asset 9 of 18 (World_radiance_5.hdr).
Exporting asset 10 of 18 (World_radiance_1.hdr).
Exporting asset 11 of 18 (World_radiance_6.hdr).
Exporting asset 12 of 18 (World_radiance_7.hdr).
Exporting asset 13 of 18 (World_radiance_8.hdr).
Exporting asset 14 of 18 (deferred_light.arm).
Exporting asset 15 of 18 (ltc_mag.arm).
Exporting asset 16 of 18 (World_radiance_9.hdr).
Exporting asset 17 of 18 (ltc_mat.arm).
Exporting asset 18 of 18 (world_pass.arm).
Compiling shader 1 of 30 (Gizmo_overlay.frag.glsl).
Compiling shader 2 of 30 (Gizmo_overlay.vert.glsl).
Compiling shader 3 of 30 (Material2_mesh.frag.glsl).
Compiling shader 4 of 30 (Material_mesh.vert.glsl).
Compiling shader 5 of 30 (Material_mesh.frag.glsl).
Compiling shader 6 of 30 (armdefault_mesh.frag.glsl).
Compiling shader 7 of 30 (armdefault_mesh.vert.glsl).
Compiling shader 8 of 30 (bloom_pass.frag.glsl).
Compiling shader 9 of 30 (blur_adaptive_pass.frag.glsl).
Compiling shader 10 of 30 (blur_edge_pass.frag.glsl).
Compiling shader 11 of 30 (blur_gaus_pass.frag.glsl).
Compiling shader 12 of 30 (compositor_pass.frag.glsl).
Compiling shader 13 of 30 (copy_mrt3_pass.frag.glsl).
Compiling shader 14 of 30 (compositor_pass.vert.glsl).
Compiling shader 15 of 30 (deferred_light_voxel.vert.glsl).
Compiling shader 16 of 30 (pass.vert.glsl).
Compiling shader 17 of 30 (pass_copy.frag.glsl).
Compiling shader 18 of 30 (pass_viewray.vert.glsl).
Compiling shader 19 of 30 (pass_viewray2.vert.glsl).
Compiling shader 20 of 30 (smaa_blend_weight.frag.glsl).
Compiling shader 21 of 30 (smaa_blend_weight.vert.glsl).
Compiling shader 22 of 30 (smaa_edge_detect.vert.glsl).
Compiling shader 23 of 30 (smaa_edge_detect.frag.glsl).
Compiling shader 24 of 30 (smaa_neighborhood_blend.frag.glsl).
Compiling shader 25 of 30 (smaa_neighborhood_blend.vert.glsl).
Compiling shader 26 of 30 (ssgi_pass.frag.glsl).
Compiling shader 27 of 30 (supersample_resolve.frag.glsl).
Compiling shader 28 of 30 (ssr_pass.frag.glsl).
Compiling shader 29 of 30 (taa_pass.frag.glsl).
Compiling shader 30 of 30 (world_pass.vert.glsl).
Compiling shader 1 of 3 (armdefault_voxel.frag.glsl).
Compiling shader 2 of 3 (armdefault_voxel.geom.glsl).
Compiling shader 3 of 3 (armdefault_voxel.vert.glsl).
Compiling shader 1 of 3 (deferred_light.frag.glsl).
Compiling shader 2 of 3 (deferred_light_voxel.frag.glsl).
Compiling shader 3 of 3 (world_pass.frag.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-text.frag.glsl).
Compiling shader 5 of 8 (painter-image.vert.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
C:\armorpaint\Sources/arm/App.hx:83: characters 3-30 : Class<Krom> has no field setSaveAndQuitCallback (Suggestion: setGamepadAxisCallback)
C:\armorpaint\Sources/arm/ui/UITrait.hx:358: characters 3-20 : Class<zui.Zui> has no field onBorderHover
C:\armorpaint\Sources/arm/ui/UITrait.hx:1267: characters 4-23 : Class<Krom> has no field setMouseCursor
C:\armorpaint\Sources/arm/ui/UITrait.hx:1268: characters 4-23 : Class<Krom> has no field setMouseCursor
C:\armorpaint\Sources/arm/ui/UITrait.hx:359: characters 3-18 : Class<zui.Zui> has no field onTextHover
C:\armorpaint\Sources/arm/ui/UITrait.hx:1278: characters 3-22 : Class<Krom> has no field setMouseCursor
C:\armorpaint\Sources/arm/ui/UINodes.hx:74: characters 3-19 : Class<zui.Nodes> has no field onLinkDrag
C:\armorpaint\Sources/arm/ui/UINodes.hx:258: characters 8-23 : zui.Zui has no field isKeyPressed
C:\armorpaint\Sources/arm/App.hx:378: characters 4-23 : Class<Krom> has no field setMouseCursor
C:\armorpaint\Sources/arm/ui/UIFiles.hx:20: characters 19-34 : Class<Krom> has no field saveDialog
C:\armorpaint\Sources/arm/ui/UIFiles.hx:20: characters 50-65 : Class<Krom> has no field openDialog

Haxe compiler error.


PS C:\armorpaint> node Kinc/make -g direct3d11 --noshaders
internal/modules/cjs/loader.js:783
    throw err;
    ^

Error: Cannot find module 'C:\armorpaint\Kinc\make'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:685:27)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}
```

**Comment by BlackGoku36** [comment]
try:
`git submodule foreach --recursive git pull origin master`
and then:
`git pull origin master`

**Comment by knightknight** [comment]
Thanks @BlackGoku36 that works!

**Comment by luboslenco** [comment]
Also updated the readme, thanks for report!
