### ISSUE TITLE
ArmorPaint not compiling on Manjaro 

### ISSUE THREAD

**Issue by John155** [armory3d/armorpaint#319]
I try to compile the Kinc part bur I get only this error message. What is the problem? 

```
node Kinc/make -g opengl --compiler clang --compile
kincfile found.
Creating Linux project files.
Compiling shader 1 of 10 (g1.frag).
Compiling shader 2 of 10 (g1.vert).
Compiling shader 3 of 10 (painter-colored.frag).
Compiling shader 4 of 10 (painter-colored.vert).
Compiling shader 5 of 10 (painter-image.frag).
Compiling shader 6 of 10 (painter-image.vert).
Compiling shader 7 of 10 (painter-text.frag).
Compiling shader 8 of 10 (painter-text.vert).
Compiling shader 9 of 10 (painter-video.frag).
Compiling shader 10 of 10 (painter-video.vert).
Compiling...
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: spawn make ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn make',
  path: 'make',
  spawnargs: [ '-j', '4' ]
}
```

I did all these steps before:
```

git clone --recursive https://github.com/armory3d/armorpaint
cd armorpaint

# Linux
node Kromx/make -g opengl
cd Kromx
```

**Comment by luboslenco** [comment]
Hello, is your clang set up properly? Are you able to compile some other code than armorpaint?

**Comment by John155** [comment]
Thanks luboslenco now it works. I had to install the lib32-clang.

**Comment by luboslenco** [comment]
Glad to hear!
