### ISSUE TITLE
Kinc/make -g direct3d11 throws error can not find module

### ISSUE THREAD

**Issue by NicTanghe** [armory3d/armorpaint#519]
``` powershell
 C:\..\armorpaint\Kromx\v8   (c401311...) ≢ +1 ~0 -0 !  node kinc/make -g direct3d11
internal/modules/cjs/loader.js:1088
  throw err;
  ^

Error: Cannot find module 'C:\tools\armorpaint\Kromx\v8\kinc\make'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1085:15)
    at Function.Module._load (internal/modules/cjs/loader.js:928:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

THere is no kink folder in v8.
I assume this is not a bug and i am doing something wrong.
What is hapening ?

**Comment by NicTanghe** [comment]
Diddent clone recursivly and dident rtfm.

**Comment by Jake-Jensen** [comment]
This is still a problem. Cloned recursively and initialized the modules correctly.
