### ISSUE TITLE
Could not build on macOS 10.15.7

### ISSUE THREAD

**Issue by burningthumb** [armory3d/armorpaint#706]
I tried to follow the build instructions for macOS and got this error:

```
const os = require("os");
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/robert/opensource/armorpaint/armorcore/make.js:1:63)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

The solution, after some googling, was to do this:

```
sudo npm clean -f 
sudo npm install -g n 
sudo n stable
```
Maybe that could be included in the instructions (maybe it is somewhere but if it was right there in the macOS instructions I'd have save half an hour.

**Comment by luboslenco** [comment]
Hello, thanks for report. Sounds like the issue was an ancient nodejs version - just installing the latest versions of listed requirements (xcode / nodejs / git) should make armorpaint compile out of the box.
